config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 resources :users
  root "home#welcome"
  resources :todos do 
    resources :todo_items , only: [:create]
  end
 
  resources :todo_items do 
    member do
      post '/complete',to: 'todo_items#mark_complete'
      post '/incomplete',to: 'todo_items#mark_incompleted'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    
    belongs_to :user,class_name:"User"
    has_many :todo_items , foreign_key: :todo_id , class_name:"TodoItem", dependent: :destroy

    def total_items 
          @total_items ||= todo_items.count
    end

    def completed_items 
        @completed_items ||= todo_items.completed.count
    end

    def percent_complete
        return 0 if total_items == 0

        (100 * completed_items.to_f / total_items ).round(1) 
    end

    def status 
        case percent_complete.to_i
        when 0
            'Not Started'
        when 100 
            'Complete'
        else
            'In progress'
        end
    end

    def badge_color 
        case percent_complete.to_i
        when 0
            'danger'
        when 100 
            'success'
        else
            'primary'
        end
    end

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord

    belongs_to :todo , class_name:"Todo"

    scope :completed , -> do
        where(completed: true)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :todos , foreign_key: :user_id , class_name: "Todo"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome 
        
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

    def create
        @todo = Todo.find(params[:todo_id])
        @todo_item = @todo.todo_items.build(description: params[:description])
        respond_to do |format|
          if @todo_item.save!
            # flash[:success]="Successfuly added new todo item !"
            format.turbo_stream
            format.html{redirect_to @todo}
          end
        end
    end

    def mark_complete
      @todo_item = TodoItem.find(params[:id])
      @todo = @todo_item.todo_id
      respond_to do |format|
        if @todo_item.update!(completed: true)
          format.turbo_stream
          format.html{redirect_to @todo}
        end
      end 
    end

    def mark_incompleted
      @todo_item = TodoItem.find(params[:id])
      @todo = @todo_item.todo_id
      respond_to do |format|
        if @todo_item.update!(completed: false)
          format.turbo_stream
          format.html{redirect_to @todo}
        end
      end 
    end

    def destroy
      @todo_item = TodoItem.find(params[:id])
      @todo = @todo_item.todo
      @todo_item.destroy
      respond_to do |format|
        format.turbo_stream
        format.html{redirect_to @todo}
      end
    end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    def show
        @todo = Todo.find(params[:id])
    end

    def index
        @todos=Todo.where(user_id: current_user.id)
    end
    def new
        @todo = Todo.new
    end
    def edit
        @todo=Todo.find(params[:id])
    end
    def create
        user = User.find( current_user.id)
        @todo = user.todos.build(todo_params)
        respond_to do |format|
          if @todo.save!
            # flash[:success]="Todo was successfuly created!!"
            format.turbo_stream
            format.html{redirect_to todos_path}
          end
        end
      end

      def update
        @todo = Todo.find(params[:id])

        respond_to do |format|
         if @todo.update!(todo_params)
            # flash[:info]="The Todo was updated!!"
            format.turbo_stream
            format.html{redirect_to todos_path}
         end
       end
     end

     def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        respond_to do |format|
           format.turbo_stream 
           format.html{redirect_to todos_path} 
        end
     end

      private 
      def todo_params 
        params.require(:todo).permit(:title)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/welcome.html.erb
<div class="card text-center">
      
  <div class="card-body d-flex flex-column align-items-center">
    <h1 class="card-title py-5">WELCOME</h1>
    <h3 class="card-subtitle text-secondary pb-0">JOIN US TO START YOUR LISTS</h3>
    <div class="d-flex pb-5"></div>
 </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
   <header class="navbar navbar-fixed-top navbar-inverse">
   <%= link_to "Home" ,root_path,id:"logo" %>
   <div class="container">
   <% if user_signed_in? %>
    <nav>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "My list",todos_path %></li>
         <li><%= button_to "logout", destroy_user_session_path , method: :delete,id:"logout-button" %></li>
       </ul>
      </nav>
   <% else %>
     <nav>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Login" ,new_user_session_path %></li>
         <li><%= link_to "Sign up", new_user_registration_path %></li>
       </ul>
      </nav>
     <% end %>
    </div>
  </header>
    <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_todo_item.html.erb
<%= turbo_frame_tag item do %>
 <% if item.completed %>
    <li>
      <span><%= item.description %></span> 
      <span><%= button_to "", incomplete_todo_item_path(item) ,class:"btn btn-info fa fa-undo" %></span>
      <br>
      <span><%= button_to "", item ,class:"btn btn-danger fa fa-times",method: :delete %>
      </span>
    </li>
    <br>
  <% else %>
    <li>
     <span><%= item.description %></span> 
     <span><%= button_to "", complete_todo_item_path(item) , class:"btn btn-success fa fa-check" %></span>
     <br>
     <span><%= button_to "", item , class:"btn btn-danger fa fa-times",method: :delete %>
     </span>
    </li>
    <br>
<% end %>
<% end %>

app/views/todo_items/create.turbo_stream.erb
<%= turbo_stream.prepend "todo_item" do %>
   <% @todo.todo_items.each do |item|  %>
    <%= render "todo_items/todo_item", item: item %>
  <% end %>
<% end %>

<%= turbo_stream.replace "item_form" do %>
 <%= form_with url:todo_todo_items_path(@todo),id:"item_form",data: {turbo: true} do |f| %>
    <%= f.text_field :description, placeholder:"Add a new todo item" %> 
    <%= f.submit "Add" , class:"btn btn-primary" %>
  <% end %>
<% end %>

<%= turbo_stream.update "todo_progress" do %>
<h2><%= @todo_item.todo.title.capitalize %>  
<span class="btn btn-<%= @todo_item.todo.badge_color %> " ><%=@todo_item.todo.status %></span>
</h2>

<p class='text-secondary m-0'><small><%= @todo_item.todo.percent_complete %>% Complete (<%= @todo_item.todo.completed_items %>/<%= @todo_item.todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @todo_item.todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<% end %>

app/views/todo_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo_item %>

<%= turbo_stream.update "todo_progress" do %>
<h2><%= @todo_item.todo.title.capitalize %>  
<span class="btn btn-<%= @todo_item.todo.badge_color %> " ><%=@todo_item.todo.status %></span>
</h2>

<p class='text-secondary m-0'><small><%= @todo_item.todo.percent_complete %>% Complete (<%= @todo_item.todo.completed_items %>/<%= @todo_item.todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @todo_item.todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<% end %>

app/views/todo_items/mark_complete.turbo_stream.erb
<%= turbo_stream.update @todo_item do  %>
 <%= render "todo_item",item: @todo_item %>
<% end %>

<%= turbo_stream.update "todo_progress" do %>
<h2><%= @todo_item.todo.title.capitalize %>  
<span class="btn btn-<%= @todo_item.todo.badge_color %> " ><%=@todo_item.todo.status %></span>
</h2>

<p class='text-secondary m-0'><small><%= @todo_item.todo.percent_complete %>% Complete (<%= @todo_item.todo.completed_items %>/<%= @todo_item.todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @todo_item.todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<% end %>

app/views/todo_items/mark_incompleted.turbo_stream.erb
<%= turbo_stream.update @todo_item do  %>
 <%= render "todo_item",item: @todo_item %>
<% end %>

<%= turbo_stream.update "todo_progress" do %>
<h2><%= @todo_item.todo.title.capitalize %>  
<span class="btn btn-<%= @todo_item.todo.badge_color %> "><%= @todo_item.todo.status %></span>
</h2>

<p class='text-secondary m-0'><small><%= @todo_item.todo.percent_complete %>% Complete (<%= @todo_item.todo.completed_items %>/<%= @todo_item.todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @todo_item.todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with model: todo, id:"todo_form", data: {turbo: true} do |f| %>
  <%= f.text_field :title ,placeholder:"Add New Todo"%>
  <%= f.submit "Submit" , class:"btn btn-success" %>
<% end %>

app/views/todos/_todo.html.erb
<div>
<%= turbo_frame_tag todo do %>
  <h3><%= link_to todo.title.capitalize ,todo,data: {turbo: true} %>  <span class="btn btn-<%= todo.badge_color %> " ><%= todo.status %></span></h3>
<p class='text-secondary m-0'><small><%= todo.percent_complete %>% Complete (<%= todo.completed_items %>/<%= todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
  <%= link_to "Edit Todo list",edit_todo_path(todo), class:"badge badge-secondary" %><br><br> 
  <%= button_to "delete", todo, method: :delete, class:"btn btn-danger fa fa-times" %>
<% end %>
</div>
<hr>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
 <%= render @todo %>
<% end %>

<%= turbo_stream.replace "todo_form" do %>
 <%= render "form" , todo: Todo.new %>
<% end %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag @todo do  %>
  <h4>Edit Todo:</h4>
   <%= render "form" , todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<div class="mx-auto w-1/2">
  <h2 class="text-2xl text-gray-900">New todo </h2>  
  <%= turbo_frame_tag "new_todo" do %>
   <%= link_to "Add new todo list",new_todo_path, class:"btn btn-info" %>
   <% end %>
   <h2>Todo List:</h2>
    <div id="todos">
      <%= render @todos %>
    </div>
</div>

app/views/todos/new.html.erb
<%= turbo_frame_tag "new_todo" do %>
<div class="card text-center">
<%= render "form",todo: @todo %>
</div>
<%  end %>

app/views/todos/show.html.erb
<span><%= link_to " Back to TodoList ",todos_path,data: {turbo: true} , class:"btn btn-primary" %></span>
<%= turbo_frame_tag "todo_progress" do %>
<h2><%= @todo.title.capitalize %>  
<span class="btn btn-<%= @todo.badge_color %> " ><%= @todo.status %></span>
</h2> 

<p class='text-secondary m-0'><small><%= @todo.percent_complete %>% Complete (<%= @todo.completed_items %>/<%= @todo.total_items %> Todo Items)</small></p>

<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= @todo.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<% end %>

<div> 
  <%= form_with url:todo_todo_items_path(@todo),id:"item_form",data: {turbo: true} do |f| %>
    <%= f.text_field :description, placeholder:"Add a new todo item" %> 
    <%= f.submit "Add" , class:"btn btn-primary" %>
  <% end %>
</div>

<h3>Todo Item List: </h3>
<ul>
<div id="todo_item" >
  <% @todo.todo_items.each do |item|  %>
    <%= render "todo_items/todo_item", item: item %>
 <% end %>
 </div>
</ul>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.update @todo do  %>
 <%= render @todo %>
<% end %>